In [1]:
import pandas as pd;

In [13]:
## Question 1

data = pd.read_csv("Sql Dataset.csv");


data.info();
data.isnull().sum();
data.dtypes;

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       200 non-null    int64
 1   customer_name  200 non-null    object
 2   order_date     200 non-null    object
 3   category       200 non-null    object
 4   sub_category   200 non-null    object
 5   product_name   200 non-null    object
 6   quantity       200 non-null    int64
 7   unit_price     200 non-null    int64
 8   total_price    200 non-null    int64
 9   region         200 non-null    object
dtypes: int64(4), object(6)
memory usage: 15.8+ KB

In [21]:
## Question 2
data.isnull().sum()
data.duplicated().sum()

## Missing Values = 0;
## Duplicate Values = 0;

np.int64(0)

In [27]:
## Question 3
data.groupby("category")["total_price"].sum()

category
Clothing       484259
Electronics    549302
Furniture      714399
Grocery        672147
Name: total_price, dtype: int64

In [31]:
## Question 4
data.sort_values(
    by= ['category','region','quantity','total_price'],
    ascending = [True,True,False ,False]
)

,order_id,customer_name,order_date,category,sub_category,product_name,quantity,unit_price,total_price,region
22,1022,Benjamin Meadows,30-04-2025,Clothing,Shoes,Shoes Job,10,2056,20560,East
157,1157,Patricia Gill,23-03-2025,Clothing,Jacket,Jacket Song,7,3915,27405,East
62,1062,Jessica Hernandez,21-05-2025,Clothing,Shoes,Shoes Care,7,3208,22456,East
59,1059,Miss Rebecca Levine,28-02-2025,Clothing,Shirt,Shirt Look,6,4794,28764,East
180,1180,Hailey Cobb,19-02-2025,Clothing,Jacket,Jacket Heart,6,4285,25710,East
...,...,...,...,...,...,...,...,...,...,...
198,1198,Marissa Aguilar,02-06-2025,Grocery,Milk,Milk Listen,6,461,2766,West
78,1078,Robin Fuller,20-01-2025,Grocery,Snacks,Snacks Into,4,247,988,West
191,1191,Tim Gross,19-03-2025,Grocery,Bread,Bread By,3,4799,14397,West
140,1140,Scott Johnston,03-03-2025,Grocery,Juice,Juice Usually,3,3539,10617,West
16,1016,Rachel Wilson,04-04-2025,Grocery,Bread,Bread Skin,2,2413,4826,West

In [30]:
## Question 5

data.corr(numeric_only=True)

             order_id  quantity  unit_price  total_price
order_id     1.000000 -0.018182    0.102267     0.099480
quantity    -0.018182  1.000000    0.047996     0.655212
unit_price   0.102267  0.047996    1.000000     0.671318
total_price  0.099480  0.655212    0.671318     1.000000